name: swinT-T_DegDistill_Imagenet
n_gpu: 1
teacher_model:
  type: MM_Classifier
  pretrained_path_jpeg: saved/jpeg/IndTrainer/swinT_MMCV_Imagenet/train/<EXP_STR>/model_best.pth
  pretrained_path_blur: saved/blur/IndTrainer/swinT_MMCV_Imagenet/train/<EXP_STR>/model_best.pth
  pretrained_path_noise: saved/noise/IndTrainer/swinT_MMCV_Imagenet/train/<EXP_STR>/model_best.pth
  args:
    type: ImageClassifier
    backbone:
      type: SwinTransformer
      arch: tiny
      img_size: 224
      drop_path_rate: 0.2
    init_cfg:
    - type: TruncNormal
      layer: Linear
      std: 0.02
      bias: 0.0
    - type: Constant
      layer: LayerNorm
      val: 1.0
      bias: 0.0
    neck:
      type: GlobalAveragePooling
    head:
      type: LinearClsHead
      num_classes: 1000
      in_channels: 768
      init_cfg: null # suppress the default init_cfg of LinearClsHead.
      loss:
        loss_weight: 1.0
        type: CrossEntropyLoss
      cal_acc: True
      topk: !!python/tuple [1, 5]
student_model:
  type: MM_Classifier
  # Pretrained model: https://mmclassification.readthedocs.io/en/latest/model_zoo.html - Swin-Transformer tiny
  pretrained_path: saved/clean/IndTrainer/swinT_MMCV_Imagenet/train/pretrained_model/swin_tiny_224_b16x64_300e_imagenet_20210616_090925-66df6be6.pth
  args:
    type: ImageClassifier
    backbone:
      type: SwinTransformer
      arch: tiny
      img_size: 224
      drop_path_rate: 0.2
    init_cfg:
    - type: TruncNormal
      layer: Linear
      std: 0.02
      bias: 0.0
    - type: Constant
      layer: LayerNorm
      val: 1.0
      bias: 0.0
    neck:
      type: GlobalAveragePooling
    head:
      type: LinearClsHead
      num_classes: 1000
      in_channels: 768
      init_cfg: null # suppress the default init_cfg of LinearClsHead.
      loss:
        loss_weight: 1.0
        type: CrossEntropyLoss
      cal_acc: True
      topk: !!python/tuple [1, 5]
data_loader:
  type: DegImagenetDataLoader
  args:
    data_dir: dataset/imagenet_50k_nondeg
    batch_size: 64
    shuffle: true
    validation_split: 0.0
    num_workers: 2
    deg_type: jpeg_blur_noise 
    deg_types: [jpeg, blur, noise] 
    deg_flag: deg
optimizer:
  type: SGD
  args:
    lr: 0.001
    weight_decay: 0.0001
loss: 
  - supervised_loss: CE
  - inheritance_loss: COS
loss_weights: [1.0, 50.0] 
metrics:
- accuracy@1
- accuracy@5
lr_scheduler:
  type: MultiStepLR
  args:
    milestones: [15, 30, 45]
    gamma: 0.1
trainer:
  type: SLDA_Trainer
  args:
    epochs: 50
    save_dir: saved/
    save_period: 1
    verbosity: 2
    monitor: max val_accuracy@1
    early_stop: 50
    tensorboard: true